### ISSUE TITLE
How to initialize a web component from JavaScript?

### ISSUE THREAD

**Issue by Woofthecat** [mdn/web-components-examples#25]
I'm trying to initialize the [popup info box web component](https://github.com/mdn/web-components-examples/tree/master/popup-info-box-web-component) using JavaScript but I can't seem to make it work.
In order to have a custom image and text, I need to use the `img` and `data-text` attributes.
```
el = document.createElement('popup-info'); //creates the popup info box
el.setAttribute('data-text', 'Test'); //and this one doesn't have any affect
document.body.append(el);
```
I suppose the `createElement` calls the constructor, but at that moment there are no attributes yet, so it just creates a basic popup-info element with no text and default image. Is there a way to initialize such web component from JavaScript?

**Comment by Leokuma** [comment]
I don't think you can pass in custom arguments directly into the constructor of a web component. It works the same as creating native elements.

Some people say it's good practice to have your constructor to just "declare" its attributes and do nothing else. All the initialization of your component could be done in another method called `_init_` or whatever you like, and then inside that method you actually initialize your component, create inner elements etc. But ultimately it depends on your needs. The component in that MDN example wasn't supposed to be created dinamically.

So what you can do is to move almost all the code from the constructor to an `init` method. You should keep in the constructor only the code related to CSS in order to prevent [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content) (it might not be needed in this case, though) and you should also keep the shadow root because that's where the style is appended to.

So all the code below would be moved to `init`:

https://github.com/mdn/web-components-examples/blob/922a3bb1f15037fa0b2d47420726b73b7cbe3790/popup-info-box-web-component/main.js#L10-L35

and

https://github.com/mdn/web-components-examples/blob/922a3bb1f15037fa0b2d47420726b73b7cbe3790/popup-info-box-web-component/main.js#L74-L76

Since `shadow` is a local variable to `constructor`, you won't have it in `init`, but you can still access it with something like `this.shadowRoot`.

Then you would use your new component like this:

```javascript
el = document.createElement('popup-info');
el.setAttribute('data-text', 'Test');
el.init(); // <---------------------------
document.body.append(el);
```
You can also make your `init` take certain arguments so that you don't have to call a couple of `setAttribute`: the `setAttribute` would be called from inside the `init` with the received arguments.

If you don't want to have to call `init`, it gets more complex. In that case you'll want to read about [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe). With MutationObserver you can make your component react to attribute changes in real time.

**Comment by Leokuma** [comment]
I found a more appropriate way to do that.

https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#Using_the_lifecycle_callbacks

You can use lifecycle callbacks. You can initialize your element in the `connectedCallback` and watch attribute changes in the `attributeChangedCallback`.

**Comment by Woofthecat** [comment]
Thanks for taking the time to write your answer! I should've been more precise though.
I'm not the one who is writing a component, I just need to init from JavaScript whatever component is given (so no markup). Since there are multiple ways to write a web component, I guess I cannot really expect that all the components are using lifecycle callbacks to initialize themselves, and the popup info box is a good example of that. 

How would I need to initialize for example the popup info box if I cannot modify its source code but I still want to show a custom text? Is there a way?

**Comment by Leokuma** [comment]
No, there's no way to do that, at least not an appropriate way.

What you could do in this case is to try to basically replicate outside of the component what the `constructor` does. But that's obviously not a good idea, and you wouldn't even be able to manipulate the shadow DOM from outside anyway.

In addition, web components were designed to be encapsulated and expose only the API the author wishes. You should be able to use it without any knowledge about its inner implementation. If the API doesn't let you "initialize" the component, that's the equivalent of the author telling you not to do that. Not all custom elements will even have the concept of initialization.

Web components have received some criticism about flexibility and extensibility. Google has created this base class in order to provide for "missing features" (or "currently unavailable features"): [lit-element](https://github.com/Polymer/lit-element). It might be worth to take a look.

**Comment by Woofthecat** [comment]
Hm... So even if I have the list of attributes with values that I need to apply, there is no simple/proper way to init a component from JavaScript in a single call?

The following works but I'm not sure if it's a good solution
```
function createFromHtml(html) {
    let temp = document.createElement('template');
    temp.innerHTML = html;
    return temp.content.firstChild;
}

//here I'll probably need to build my own logic to create a string
elHtml = '<popup-info img="test.png" data-text="Test"></popup-info>';
el  = createFromHtml(elHtml);
```
Feels like there should be a better way of doing this.

**Comment by Leokuma** [comment]
That was a good idea. Now I understand more clearly what you want to do. I agree that there should be a better way of doing that.

That's not that big of a deal though, because when you call `createElement`, the element is still not rendered: it exists only in memory. The next step in its lifecycle happens when it gets attached to the DOM (`connectedCallback`), which is almost like a second initialization. Only then the element is actually rendered.

From a design perspective, I see the constructor's role as to provide only the very minimum in order for the element to exist. So I still believe it comes down to designing the custom element properly rather than working around its limitations later. Lifecycle callbacks exist for a reason and they should guide design decisions.

**Comment by Woofthecat** [comment]
While the element is not rendered with `createElement`, it seems like that it calls the constructor anyways. So if we are talking about a component that initializes itself with the attributes from the constructor only, then after `createElement` there's nothing I can do, unless I can trigger the constructor again after the attributes are set... Is that even possible?

From a design perspective I agree that it's not the best approach, but I also understand why someone would prefer it over callbacks. Unfortunately I'm not the one writing these components, I just need to add them on request.

**Comment by Leokuma** [comment]
> [...] unless I can trigger the constructor again after the attributes are set... Is that even possible?

I don't think so, and I wouldn't even bother because it looks like an antipattern. Your first suggestion of using `innerHTML` is good enough IMO. I've seen a few libraries generate HTML as string just like that.

You can make your `createFromHtml` function a little more flexible and easy to use. Something like this:

```javascript
function createElementWithAttributes(el, attrs) {
    let temp = document.createElement('template');
    temp.innerHTML = `<${el} ${Object.entries(obj).map(([key, value]) => `${key}="${value}"`).join(' ')}></${el}>`;
    return temp.content.firstChild;
}

let el = createElementWithAttributes('popup-info', {img: 'test.png', 'data-text': 'Text', foo: true, bar: 17});

// OR

let attrs = {};
attrs.img = 'text.png';
attrs['data-text'] = 'Text';
attrs.foo = true;
attrs.bar = 17;

el = createElementWithAttributes('popup-info', attrs);
```

You can also return just a string instead of an element and then append the string directly to the DOM. That way you don't need a temporary `<template>`.

**Comment by Woofthecat** [comment]
I'll go with this, thanks!
